## Environment name which should equal to Git branch name

# Production website
main:

  # SSH user to be used in deployment
  user: root

  # Server hostname or IP address for deployment
  hostname: 63.32.105.71
  
  # Path to deploy.
  deploy_path: /opt/easyengine/sites/www.sofair.io/app/htdocs

# Development (development) website
develop:
  user: root
  hostname: 63.32.105.71
  deploy_path: /opt/easyengine/sites/development.sofair.io/app/htdocs

# Devops (staging) website
devops:
  user: root
  hostname: 63.32.105.71
  deploy_path: /opt/easyengine/sites/staging.sofair.io/app/htdocs